name: Build
on:
  push:
    branches:
      - main
jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build app
        run: ./gradlew build
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
