name: Build
on:
  push:
    branches:
      - main
jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - name: Build app
        run: ./gradlew assembleDebug
      - name: Archive release artifact
        uses: actions/upload-artifact@v4
        with:
          name: pandplay-debug
          path: app/build/outputs/apk/debug/pandplay-debug.apk
