name: Create release
on:
  push:
    tags:
      - 'v[0-9]+.*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release create "${GITHUB_REF_NAME}" --generate-notes
