name: Build debug APK
on:
  push:
    branches:
      - main
jobs:
  debug-apk:
    uses: jre/github-stuff/.github/workflows/build-apk.yaml@v1
    permissions:
      contents: read
    with:
      gradle-task: assembleDebug
      artifact-name: pandplay-debug-${{ github.sha }}.apk
      artifact-path: app/build/outputs/apk/debug/pandplay-debug.apk
      key-alias: pandplay_signing
    secrets:
      keystore-base64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
      keystore-password: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
